[_]
schema-version = "0.2"

[io.buildpacks]
include = [
    "target/resulter-api-*.jar"
]

[[io.buildpacks.group]]
id = "paketo-buildpacks/java"
version = "~17.0"

[build]
[[build.env]]
name = "BP_JVM_VERSION"
value = "21"

[metadata]
name = "resulter-backend"
version = "4.6.4"
